#!/bin/sh
# Creates an "Install deepin" icon on the live session tested with:

# We query xdg-user-dir because the Desktop directory has different
# names for different languages
DESKTOP=$(xdg-user-dir DESKTOP)

# Create ~/Desktop just in case this runs before the xdg folder
# creation script.
mkdir -p $DESKTOP

cp /usr/share/applications/install-deepin.desktop $DESKTOP
