#!/bin/sh

# 备份分区文件
sudo mv /etc/fstab /etc/fstab.orig.calamares

# 以root身份运行 calamares 的安装程序
xhost +si:localuser:root
pkexec calamares
xhost -si:localuser:root

# 还原分区文件
sudo mv /etc/fstab.orig.calamares /etc/fstab
