#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

cat << EOF > $CHROOT/etc/apt/sources.list
deb https://community-packages.deepin.com/beige/ crimson main commercial community
EOF

exit 0
